sonar.projectKey=law-ai
sonar.projectName=Law AI
sonar.projectVersion=1.0

# frontend source
sonar.sources=frontend/src,backend

# exclude test files and node_modules from analysis
sonar.exclusions=**/node_modules/**,**/build/**,**/*.test.js,**/reportWebVitals.js,**/setupTests.js

# test report paths
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
